[package]
name = "hello-wasm"
version = "0.1.0"
authors = ["Noprop <12greg21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
